apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_URL: bW9uZ29kYitzcnY6Ly9ub3R1c2VyOm5vdHVzZXJAZmlsZW1hbmFnZXIuczFrcm9yZS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
