name: Python formatting

on: [push]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install black
      - name: Check formatting
        run: black --check .
